apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXNxbA==  # Base64 encoded 'postgresql'
  POSTGRES_USER: YWRtaW4=         # Base64 encoded 'admin'
  POSTGRES_PASSWORD: c2VjcmV0     # Base64 encoded 'secret'
